### ISSUE TITLE
Custom encoders

### ISSUE THREAD

**Issue by aptwebapps** [jsocol/django-jsonview#19]
I forked and added a small patch, https://github.com/aptwebapps/django-jsonview/commit/447f240bef1cb288a24888f70a90f8e04e0bc945 , to enable custom encoders. I'd send a pull request, but it needs polishing (tests, Readme updates).  Before I do that, are you interested in the idea?

**Comment by aptwebapps** [comment]
Small update: https://github.com/aptwebapps/django-jsonview/commit/f191c00aa43ef2241faefe78bd6d4e5d6d9a2be8

**Comment by jsocol** [comment]
I like the idea but as I was working it through, I think there's a better option

Not all json modules (especially `ujson`, `yajl` and other C/C++-based modules) support the `cls` kwarg, that's why `_dump_json` needs some kind of guard. But they do often support other arguments.
 
Which actually makes me think that instead of doing this specific argument, it would make more sense to do some kind of `JSON_{LOAD|DUMP}_OPTIONS` setting(s) that let users specify any number of kwargs to the `{module}.loads` and `{module}.dumps` methods, regardless of the module. It could even default to `{'cls': django.core.serializers.json.DjangoJSONEncoder}` to keep the current default of using Django's encoder. People like me who opt for the faster, less flexible encoders could just set it to `None`, then `_dump_json` would do something like `if OPTIONS is not None: return json.dumps(obj, **OPTIONS); return json.dumps(obj)`.

**Comment by aptwebapps** [comment]
That sounds good. I'm in a bit of a crunch right now so I'll stick with my fork as it meets my needs. But in a few weeks I'll put something together as you suggest and submit a pull request.

**Comment by jsocol** [comment]
Now supported as of v0.5.0 / 60fefdd264d91d6f87fb35aad09b08f3a596563d
