### ISSUE TITLE
Django Model Instance 

### ISSUE THREAD

**Issue by Amar-Chaudhari** [jsocol/django-jsonview#24]
How can I return model instance using jsonview ?

**Comment by jsocol** [comment]
There are a couple of options, all of which are out of scope of django-jsonview:

* I usually add a `MyModel.to_dict()` method, which lets me be _very_ explicit about which fields are returned, and any transformations (like printing dates in ISO8601). Then I return `obj.to_dict()` instead of just `obj`.
* If all the attributes are JSON serializable (by default jsonview uses the Django JSON encoder which can handle datetime objects, too) you could, in theory, just return `obj.__dict__` (though I don't recommend that).
* You could write a [custom JSON encoder](https://docs.python.org/2/library/json.html#json.JSONEncoder) that handles your types, and [use that encoder](https://github.com/jsocol/django-jsonview#configuring-json-output).
